import {test} from 'node:test';import assert from 'node:assert/strict';
import {testDatabase,fixtureConfig,fixtureOrganization} from './database.js';import {FieldRepository} from '../src/persistence/field.js';import {SupabaseRepositories} from '../src/persistence/supabase.js';
import {commandDefinitions} from '../src/runtime/commands.js';import {route} from '../src/runtime/bot.js';import {repairResources,type ManagedResource} from '../src/resources.js';import {BridgeCoordinator,type BridgeRow} from '../src/bridge.js';import {DurableDelivery,IntelligencePipeline,type ContactRow} from '../src/intelligence.js';
import {FundsService} from '../src/services.js';
import {needsConfirmation,handleConfirmation} from '../src/runtime/confirmation.js';
test('Final audit: every registered command routes to its production handler, with no unavailable namespace',async()=>{
 let count=0;for(const c of commandDefinitions('organization') as any[]){for(const sub of c.options?.length?c.options:[{name:''}]){
  const i:any={guildId:'g',id:'event',channelId:'commands',user:{id:'actor'},commandName:c.name,memberPermissions:{has:()=>true},guild:{members:{async fetch(){throw new Error('handler reached');}},roles:{async fetch(){return new Map();}}},isButton:()=>false,isAnySelectMenu:()=>false,isModalSubmit:()=>false,isStringSelectMenu:()=>false,isChatInputCommand:()=>true,async deferReply(){},async reply(){},options:new Proxy({getSubcommand:()=>sub.name},{get:(target:any,key:string)=>target[key]??(()=>null)})};
  const config={...fixtureConfig(),commandNamespace:'organization',modules:{atlas:true,supply:true,briefings:true,patrols:true}},repos:any=new Proxy({load:async()=>config,list:async()=>[]},{get:(target:any,key:string)=>target[key]??(async()=>{throw new Error('handler reached');})});
  if(c.name==='ping')await route(i,{} as any,repos);
  else if(needsConfirmation(i)){if(c.name==='funds'&&sub.name==='undo-last')repos.recentHistory=async()=>[];let prompt:any;i.reply=async(p:any)=>{prompt=p;};await route(i,{} as any,repos);assert.match(prompt.content,/Confirm/);const click={...i,customId:prompt.components[0].components[0].custom_id,isChatInputCommand:()=>false,isButton:()=>true};await assert.rejects(handleConfirmation(click,next=>route(next,{} as any,repos,true)),/handler reached/);}
  else await assert.rejects(route(i,{async start(){throw new Error('handler reached');}} as any,repos),/handler reached/);count++;
 }}assert.ok(count>100);
});
test('Final audit: resource creation fences ambiguous category sends and recovers channels without duplicate creation',async()=>{
 const rows:ManagedResource[]=[];let creates=0;const registry={async list(){return rows;},async put(row:ManagedResource){const index=rows.findIndex(r=>r.key===row.key);if(index<0)rows.push(row);else rows[index]=row;}};
 const provisioner={async exists(){return true;},async create(){creates++;throw new Error('Response lost');},async restorePermissions(){}};
 const specs=[{key:'CORE_CATEGORY' as const,name:'Core',kind:'CATEGORY' as const}];await assert.rejects(repairResources('g',specs,registry,provisioner));assert.ok(rows[0]!.discordId.startsWith('pending:'));await assert.rejects(repairResources('g',specs,registry,provisioner),/uncertain outcome/);assert.equal(creates,1);
 await repairResources('g',specs,registry,{...provisioner,async recover(){return 'original-category';}});assert.equal(creates,1);assert.equal(rows[0]!.discordId,'original-category');
});
test('Final audit: all tables have RLS, service-role RPC paths work and anonymous execution is denied',async()=>{const {db,client}=await testDatabase(),store=new SupabaseRepositories(client);try{
 await db.exec('set role service_role');await store.saveOrganization({...fixtureConfig(),modules:{atlas:true,supply:true,briefings:true,patrols:true}},fixtureOrganization(),'admin');const t=await store.trailmark('g','create','admin',undefined,{name:'Camp'});await store.trailmark('g','report','member',t.id,{id:crypto.randomUUID(),body:'Local'});await store.intelligence('g','contact-create','admin',crypto.randomUUID(),{name:'Contact',kind:'CONTACT'});await store.createLinkCode('g','member',new Date(Date.now()+600000).toISOString());await store.workflow('g','strongbox','submit','member',crypto.randomUUID(),{contents:'Goods',source:'event'});await store.optional('g','supply','create','admin',crypto.randomUUID(),{title:'Food'});await db.exec('reset role');
 assert.deepEqual((await db.query("select relname from pg_class where relnamespace='public'::regnamespace and relkind='r' and not relrowsecurity")).rows,[]);
 assert.deepEqual((await db.query("select proname from pg_proc where pronamespace='public'::regnamespace and has_function_privilege('anon',oid,'execute')")).rows,[]);
 await db.exec('set role anon');await assert.rejects(db.query('select * from intel_reports'));await assert.rejects(db.query('select * from report_topics'));await db.exec('reset role');
}finally{await db.close();}});
test('Final audit: upgrade preserves legacy topics, consolidates storage and catch-all reset respects unique registry IDs',async()=>{
 const {db,client}=await testDatabase(async(db,file)=>{if(file==='011_production_audit.sql')await db.exec("insert into server_config(guild_id,organization_name,command_namespace) values('old','Old','old');insert into report_topics(id,guild_id,name,keywords,channel_resource_key) values('99999999-9999-4999-8999-999999999999','old','Knowledge',array['history'],'EXTRA:old-topic');insert into managed_resources values('old','EXTRA:old-topic','channel','CHANNEL',null);");});try{
  const store=new FieldRepository(client),topics=await store.intelligence<any[]>('old','topics','admin');assert.equal(topics.length,1);assert.equal(topics[0].name,'Knowledge');assert.equal((await db.query<{resource_key:string}>("select resource_key from managed_resources where guild_id='old'")).rows[0]!.resource_key,'REPORT_TOPIC:'+topics[0].id);assert.equal((await db.query('select * from report_topics')).rows.length,1);
  await db.exec("insert into managed_resources values('old','REPORT_CATCHALL','catchall','CHANNEL',null)");await store.intelligence('old','catchall-reset','admin');assert.equal((await db.query("select * from managed_resources where resource_key='REPORT_CATCHALL'")).rows.length,0);
 }finally{await db.close();}
});
test('Final audit: Funds aggregates and bounded history preserve the original ledger semantics',async()=>{const {db,client}=await testDatabase(),store=new SupabaseRepositories(client);try{
 await store.saveOrganization(fixtureConfig(),fixtureOrganization(),'admin');await db.query("insert into fund_ledger(id,guild_id,amount,kind,actor_id,note) values($1,'g',12.5,'DEPOSIT','member','Contribution'),($2,'g',-2.25,'SPEND','admin','Supplies')",[crypto.randomUUID(),crypto.randomUUID()]);assert.equal(await new FundsService(store).balance('g'),10.25);assert.equal((await store.recentHistory('g',1)).length,1);assert.equal(await store.balanceTotal('other'),0);
}finally{await db.close();}});
test('Final audit: normal/confidential reports traverse HQ, local Intel, Contacts and the authenticated bridge without duplicate sends',async()=>{const {db,client}=await testDatabase(),store=new FieldRepository(client);try{
 await store.saveOrganization(fixtureConfig('a'),fixtureOrganization('a'),'admin');await store.saveOrganization(fixtureConfig('b'),{...fixtureOrganization('b'),ranks:[],edges:[],branches:[]},'admin');await store.bridge<BridgeRow>('a','setup','admin',undefined,{remote:'b',name:'B',protocol:'codex-v1'});await store.bridge('b','setup','admin',undefined,{remote:'a',name:'A',protocol:'codex-v1'});const t=await store.trailmark('a','create','admin',undefined,{name:'Field'}),contact=await store.intelligence<ContactRow>('a','contact-create','admin',crypto.randomUUID(),{name:'Local contact',kind:'CONTACT'});const sends:string[]=[],publisher={async send(channel:string,key:string){sends.push(channel+key);return 'message-'+sends.length;},async recover(){return undefined;}},pipeline=new IntelligencePipeline(store,new DurableDelivery(store,publisher),{async topic(){return 'reports';},async contact(){return 'contacts';}});
 const normal=crypto.randomUUID(),secret=crypto.randomUUID();for(const [id,body]of [[normal,'Normal report'],[secret,'[cOnFiDeNtIaL] Local report']]){await store.trailmark('a','report','member',t.id,{id,body});await store.intelligence('a','report-links','member',id,{ids:[contact.id]});assert.equal(await pipeline.process('a',id!),false);await store.intelligence('a','report-hq','member',id);await pipeline.process('a',id!);}
 assert.equal(sends.length,4);await new BridgeCoordinator(store).drain('a','[CONFIDENTIAL]');await pipeline.batch('b');assert.equal(sends.length,5);assert.equal((await store.intelligence<any[]>('b','reports','admin')).length,1);await pipeline.batch('a');await new BridgeCoordinator(new FieldRepository(client)).drain('a','[CONFIDENTIAL]');await pipeline.batch('b');assert.equal(sends.length,5);
 const b=await store.trailmark('b','create','admin',undefined,{name:'Other'});await assert.rejects(db.query("insert into trailmark_sessions(id,guild_id,trailmark_id,discord_member_id,expires_at,state) values($1,'a',$2,'member',now()+interval '1 hour','PENDING')",[crypto.randomUUID(),b.id]),/different guild/);
}finally{await db.close();}});
