import {test} from 'node:test';import assert from 'node:assert/strict';import {Collection} from 'discord.js';
import {testDatabase,fixtureConfig,fixtureOrganization} from './database.js';import {FieldRepository} from '../src/persistence/field.js';import {DurableSummary} from '../src/workflows.js';import {handleWorkflows} from '../src/runtime/handlers/workflows.js';
async function fixture(){const {db,client}=await testDatabase(),store=new FieldRepository(client),org=fixtureOrganization();org.duties=[{guildId:'g',roleId:'duty',displayName:'Coordinator'}];await store.saveOrganization(fixtureConfig(),org,'admin');for(const id of ['member','mentor','other'])await store.commitMember(undefined,{guildId:'g',memberId:id,displayName:id,status:'ACTIVE',version:0,dutyIds:[],entryIds:[],notes:[]},'admin','MEMBER_SYNCED','Test');return {db,client,store};}
test('Phase 8 Strongbox and configured-duty applications persist submit/review/withdraw decisions',async()=>{const {db,store}=await fixture();try{
 const id=crypto.randomUUID();await store.workflow('g','strongbox','submit','member',id,{contents:'Inventory',source:'interaction'});assert.equal((await store.workflow('g','strongbox','list','other')).length,0);let row=await store.workflow('g','strongbox','process','admin',id,{note:'Recorded'});assert.equal(row.status,'PROCESSED');assert.equal(row.reviewed_by,'admin');assert.equal((await store.workflow('g','strongbox','reject','admin',id)).status,'PROCESSED');await assert.rejects(store.workflow('other','strongbox','get','member',id));
 await store.workflow('g','application','setup','admin',undefined,{enabled:true,question:'Why?'});const a=crypto.randomUUID();await store.workflow('g','application','apply','member',a,{duty:'duty',answers:{response:'Experience'}});await assert.rejects(store.workflow('g','application','apply','member',crypto.randomUUID(),{duty:'duty',answers:{response:'Duplicate'}}));await assert.rejects(store.workflow('g','application','withdraw','other',a));await store.workflow('g','application','withdraw','member',a);const b=crypto.randomUUID();await store.workflow('g','application','apply','member',b,{duty:'duty',answers:{response:'New'}});row=await store.workflow('g','application','approve','admin',b);assert.equal(row.status,'APPROVED');assert.equal(row.reviewed_by,'admin');await assert.rejects(store.workflow('g','application','apply','other',crypto.randomUUID(),{duty:'unconfigured',answers:{response:'No'}}));
}finally{await db.close();}});
test('Phase 8 mentorship lifecycle rejects duplicate active requests and cycles; poll and board operations persist',async()=>{const {db,client,store}=await fixture();try{
 const id=crypto.randomUUID();await store.workflow('g','mentorship','looking-for','member',id);await assert.rejects(store.workflow('g','mentorship','looking-for','member',crypto.randomUUID()));await store.workflow('g','mentorship','propose','mentor',id,{mentor:'mentor'});await store.workflow('g','mentorship','assign','admin',id,{mentor:'mentor'});await assert.rejects(store.workflow('g','mentorship','assign','admin',id,{mentor:'other'}));const second=crypto.randomUUID();await store.workflow('g','mentorship','looking-for','mentor',second);await assert.rejects(store.workflow('g','mentorship','assign','admin',second,{mentor:'member'}),/cycle/);await store.workflow('g','mentorship','end','admin',id);assert.equal((await new FieldRepository(client).workflow('g','mentorship','get','member',id)).status,'ENDED');
 const poll=crypto.randomUUID();await store.workflow('g','vote','open','admin',poll,{title:'Choose',options:['A','B'],tier:'LEVEL_1'});await store.workflow('g','vote','cast','member',poll,{selection:'A'});await assert.rejects(store.workflow('g','vote','cast','member',poll,{selection:'B'}));await store.workflow('g','vote','close','admin',poll);await assert.rejects(store.workflow('g','vote','cast','other',poll,{selection:'B'}));assert.deepEqual((await store.workflow('g','vote','audit','admin',poll)).counts,{A:1});
 const item=crypto.randomUUID();await store.workflow('g','assignment','open','admin',item,{title:'Survey',description:'Gather observations'});await store.workflow('g','assignment','claim','member',item);assert.deepEqual((await store.workflow('g','assignment','claim','member',item)).payload.claimed,['member']);await store.workflow('g','assignment','unclaim','member',item);await store.workflow('g','assignment','close','admin',item);await assert.rejects(store.workflow('g','assignment','claim','member',item));
}finally{await db.close();}});
test('Phase 8 durable public summary creates once, edits, replaces confirmed deletion and survives restart',async()=>{const {db,client,store}=await fixture();try{
 const messages=new Map<string,string>();let sends=0;const editor={async send(_channel:string,_key:string,body:string){const id='message-'+ ++sends;messages.set(id,body);return id;},async recover(){return undefined;},async edit(_channel:string,id:string,body:string){if(!messages.has(id))return false;messages.set(id,body);return true;}};
 let summary=new DurableSummary(store,editor);const first=await summary.refresh('g','funds','channel','Balance 1');await summary.refresh('g','funds','channel','Balance 2');assert.equal(sends,1);assert.equal(messages.get(first),'Balance 2');messages.delete(first);summary=new DurableSummary(new FieldRepository(client),editor);const second=await summary.refresh('g','funds','channel','Balance 3');assert.notEqual(first,second);await summary.refresh('g','funds','channel','Balance 4');assert.equal(sends,2);assert.equal((await store.workflow('g','message','get','admin',undefined,{key:'funds'})).message_id,second);
}finally{await db.close();}});
test('Phase 8 actual recruitment handler deduplicates welcome and invites and vote handler rejects ineligible voters',async()=>{const {db,store}=await fixture();try{
 let sends=0,invites=0;let allowed=true;const channel:any={id:'notice',isTextBased:()=>true,async send(){return {id:'message-'+ ++sends};},async fetchInvites(){return new Collection();},async createInvite(options:any){assert.equal(options.maxAge,86400);assert.equal(options.maxUses,1);assert.equal(options.unique,true);invites++;return {code:'example-code'};}};
 const guild:any={id:'g',client:{user:{id:'bot'}},channels:{async fetch(){return channel;}},roles:{async fetch(){return new Collection();}},members:{async fetch(){return {roles:{cache:new Collection()},permissions:{has:()=>allowed}};}}};
 const repos=Object.assign(store,{async list(){return [{guildId:'g',key:'NOTICE_BOARD',discordId:'notice',kind:'CHANNEL'}];},async load(){return fixtureConfig();},async permissionRoles(){return [];} });let action='welcome',reply:any;
 const i:any={id:'recruit-operation',guild,guildId:'g',user:{id:'admin'},commandName:'recruit',options:{getSubcommand:()=>action,getUser:()=>({id:'member',username:'Member',createDM:async()=>channel})},isModalSubmit:()=>false,async deferReply(){},async editReply(x:any){reply=x;}};
 await handleWorkflows(i,repos as any);await handleWorkflows(i,repos as any);assert.equal(sends,1);action='invite';await handleWorkflows(i,repos as any);await handleWorkflows(i,repos as any);assert.equal(invites,1);assert.match(reply.content,/discord.gg/);
 const poll=crypto.randomUUID();await store.workflow('g','vote','open','admin',poll,{title:'Restricted',options:['A','B'],tier:'LEVEL_3'});allowed=false;await assert.rejects(handleWorkflows({...i,customId:`flow:admin:vote:ballot:${poll}`,values:['A']},repos as any),/permission/);
}finally{await db.close();}});
