import {test} from 'node:test';import assert from 'node:assert/strict';import {Collection} from 'discord.js';
import {testDatabase,fixtureConfig,fixtureOrganization} from './database.js';import {FieldRepository} from '../src/persistence/field.js';import {SupabaseRepositories} from '../src/persistence/supabase.js';import {AtlasRuntime,handleAtlas} from '../src/runtime/atlas.js';import {handleOptional} from '../src/runtime/handlers/optional.js';
const config=(guild='g')=>({...fixtureConfig(guild),modules:{atlas:true,briefings:true,patrols:true,supply:true}});
test('Phase 9 optional modules gate persisted Supply lifecycle, allocation/undo, Briefings, Patrol and Reference',async()=>{const {db,client}=await testDatabase(),store=new FieldRepository(client);try{
 await store.saveOrganization(fixtureConfig(),fixtureOrganization(),'admin');await assert.rejects(store.optional('g','supply','create','admin',crypto.randomUUID(),{title:'Off'}),/disabled/);await store.saveOrganization(config(),fixtureOrganization(),'admin');await store.commitMember(undefined,{guildId:'g',memberId:'member',displayName:'Member',status:'ACTIVE',notes:[],version:0,dutyIds:[],entryIds:[]},'admin','MEMBER_SYNCED','Test');
 const id=crypto.randomUUID();await store.optional('g','supply','create','admin',id,{title:'Food units'});const operation=crypto.randomUUID();await store.optional('g','supply','log','member',id,{quantity:10,operation});assert.equal((await store.optional('g','supply','log','member',id,{quantity:10,operation})).stock,10);await store.optional('g','supply','redistribute','admin',id,{quantity:3,recipient:'member',operation:crypto.randomUUID()});await assert.rejects(store.optional('g','supply','undo-last','member',id,{operation:crypto.randomUUID()}));await store.optional('g','supply','log','member',id,{quantity:2,operation:crypto.randomUUID()});assert.equal((await store.optional('g','supply','undo-last','member',id,{operation:crypto.randomUUID()})).stock,7);await store.optional('g','supply','close','admin',id);await assert.rejects(store.optional('g','supply','log','member',id,{quantity:1,operation:crypto.randomUUID()}));await store.optional('g','supply','reopen','admin',id);assert.equal((await store.optional('g','supply','contributors','member',id)).contributors[0].quantity,10);await store.optional('g','supply','cancel','admin',id);await assert.rejects(store.optional('g','supply','reopen','admin',id));
 await store.optional('g','briefing','setup','admin',undefined,{heading:'Dispatch'});const briefing=crypto.randomUUID();await store.optional('g','briefing','send','admin',briefing,{title:'Update',body:'News'});assert.equal((await store.optional('g','briefing','get','member',briefing)).body,'News');
 await store.trailmark('g','create','admin',undefined,{name:'Outpost'});assert.ok((await store.optional('g','patrol','suggest','member',crypto.randomUUID())).trailmark_id);
 const reference=await store.optional('g','reference','save','admin',undefined,{key:'conduct',title:'Conduct',body:'Treat others respectfully.'});assert.equal((await store.optional('g','reference','get','member',reference.id)).body,'Treat others respectfully.');
}finally{await db.close();}});
test('Phase 9 Atlas RPC names, link expiry, service-only authorization, scoped queues and leases',async()=>{const {db,client}=await testDatabase(),store=new SupabaseRepositories(client);try{
 await store.saveOrganization(config(),fixtureOrganization(),'admin');const code=await store.createLinkCode('g','member',new Date(Date.now()+600000).toISOString());assert.equal(code.length,32);const stored=(await db.query<{code_hash:string}>('select code_hash from atlas_discord_links')).rows[0]!.code_hash;assert.notEqual(stored,code);
 await store.atlasRpc('claim_atlas_discord_link',{p_guild_id:'g',p_atlas_user_id:'account',p_code:code});await assert.rejects(store.atlasRpc('claim_atlas_discord_link',{p_guild_id:'g',p_atlas_user_id:'other',p_code:code}));const expired=await store.createLinkCode('g','other',new Date(Date.now()+1000).toISOString());await db.exec("update atlas_discord_links set expires_at=now()-interval '1 second' where claimed_at is null");await assert.rejects(store.atlasRpc('claim_atlas_discord_link',{p_guild_id:'g',p_atlas_user_id:'other',p_code:expired}));
 const t=await store.trailmark('g','create','admin',undefined,{name:'Camp'}),id=crypto.randomUUID();await store.atlasRpc('request_atlas_trailmark_access',{p_guild_id:'g',p_atlas_user_id:'account',p_trailmark_id:t.id,p_request_id:id});assert.equal((await store.claimAccess('g'))[0]!.memberId,'member');assert.equal((await store.claimAccess('g')).length,0);await db.exec("update atlas_trailmark_access_requests set lease_until=now()-interval '1 second'");assert.equal((await store.claimAccess('g'))[0]!.id,id);await store.completeAccess(id,true);assert.equal((await store.claimAccess('g')).length,0);
 await store.atlasRpc('upsert_atlas_live_position',{p_guild_id:'g',p_atlas_user_id:'account',p_position:{x:1,y:2,z:3}});assert.equal((await store.atlasRpc('get_atlas_live_positions',{p_guild_id:'g'})).length,1);await store.atlasRpc('remove_atlas_live_position',{p_guild_id:'g',p_atlas_user_id:'account'});assert.equal((await store.atlasRpc('get_atlas_live_positions',{p_guild_id:'g'})).length,0);
 await db.exec('set role anon');await assert.rejects(db.query("select claim_pending_atlas_trailmark_access_requests('g')"));await db.exec('reset role');
}finally{await db.close();}});
test('Phase 9 real Atlas runtime grants access, captures drops, synchronizes profiles and heartbeats independently per guild',async()=>{const {db,client}=await testDatabase(),store=new SupabaseRepositories(client);try{
 await store.saveOrganization(config(),fixtureOrganization(),'admin');await store.saveOrganization(config('other'),{...fixtureOrganization('other'),ranks:[],branches:[],edges:[]},'admin');const code=await store.createLinkCode('g','member',new Date(Date.now()+600000).toISOString());await store.atlasRpc('claim_atlas_discord_link',{p_guild_id:'g',p_atlas_user_id:'account',p_code:code});const t=await store.trailmark('g','create','admin',undefined,{name:'Camp'});await store.atlasRpc('request_atlas_trailmark_access',{p_guild_id:'g',p_atlas_user_id:'account',p_trailmark_id:t.id,p_request_id:crypto.randomUUID()});
 const channels=new Collection<string,any>();const guild:any={id:'g',roles:{async fetch(){return new Collection();}},members:{async fetch(){return {displayName:'Member',displayAvatarURL:()=> 'https://example.invalid/avatar',presence:{status:'online'},roles:{cache:new Collection()},permissions:{has:()=>true}};},async fetchMe(){return {id:'bot'};}},channels:{async fetch(id?:string){return id?channels.get(id):channels;},async create(data:any){const cache=new Collection<string,any>();const channel={...data,id:'camp',permissionOverwrites:{cache,async edit(id:string){cache.set(id,{id,type:1});},async delete(id:string){cache.delete(id);}}};channels.set(channel.id,channel);return channel;}}};
 const repos:any=Object.assign(store,{async load(id:string){return config(id);},async list(){return [];},async permissionRoles(){return [];}}),runtime=new AtlasRuntime(repos);await runtime.poll({...guild,id:'other'});assert.equal((await db.query<{status:string}>('select status from atlas_trailmark_access_requests')).rows[0]!.status,'PENDING');await runtime.poll(guild);assert.equal((await db.query<{status:string}>('select status from atlas_trailmark_access_requests')).rows[0]!.status,'COMPLETED');assert.equal((await db.query('select * from atlas_visits')).rows.length,1);assert.equal((await db.query<{presence:string}>('select presence from atlas_profiles')).rows[0]!.presence,'online');
 const drop=crypto.randomUUID();await store.atlasRpc('submit_atlas_trailmark_drop',{p_guild_id:'g',p_atlas_user_id:'account',p_trailmark_id:t.id,p_drop_id:drop,p_payload:{body:'Observation'}});await new AtlasRuntime(repos).poll(guild);assert.equal((await store.intelligence<any>('g','report-get','member',drop)).body,'Observation');await new AtlasRuntime(repos).poll(guild);assert.equal((await db.query('select * from atlas_visits')).rows.length,1);await store.trailmark('g','leave','member');await runtime.poll(guild);assert.ok((await db.query<{ended_at:string}>('select ended_at from atlas_visits')).rows[0]!.ended_at);
 repos.load=async()=>fixtureConfig();await runtime.poll(guild);await assert.rejects(handleAtlas({guildId:'g',async deferReply(){}},repos),/disabled/);
}finally{await db.close();}});
test('Phase 9 production Briefing and Reference handlers use stored settings and idempotent delivery',async()=>{const {db,client}=await testDatabase(),store=new FieldRepository(client);try{
 await store.saveOrganization(config(),fixtureOrganization(),'admin');await store.optional('g','briefing','setup','admin',undefined,{heading:'Dispatch'});let sends=0,reply:any;const guild:any={id:'g',client:{user:{id:'bot'}},members:{async fetch(){return {roles:{cache:new Collection()},permissions:{has:()=>true}};}},roles:{async fetch(){return new Collection();}},channels:{async fetch(){return {id:'desk',isTextBased:()=>true,async send(){return {id:'message-'+ ++sends};}};}}};const repos:any=Object.assign(store,{async load(){return config();},async permissionRoles(){return [];},async list(){return [{key:'DISPATCH_DESK',discordId:'desk'}];}});
 const i:any={id:'briefing-event',guildId:'g',guild,user:{id:'admin'},customId:'optional:admin:briefing:send-save:new',fields:{getTextInputValue:(key:string)=>key==='title'?'Today':'News'},isModalSubmit:()=>true,async deferReply(){},async editReply(x:any){reply=x;}};await handleOptional(i,repos);await handleOptional(i,repos);assert.equal(sends,1);
 await handleOptional({...i,customId:'optional:admin:reference:edit-save:new',fields:{getTextInputValue:(key:string)=>({key:'guide',title:'Guide',body:'Reference text'}[key])}},repos);assert.match(reply.content,/Saved/);assert.equal((await store.optional('g','reference','list','admin')).length,1);
}finally{await db.close();}});
