import test from "node:test";import assert from "node:assert/strict";
import {AtlasService,BridgeService,ContactForwardingService,FundsService,IntelService,MemberService,TrailmarkService,type AtlasDrop,type AtlasRequest,type LedgerEntry,type StoredReport,type TrailmarkSession}from"../src/index.js";

test("Trailmark grants replace a member's active session and expiry is guild-aware",async()=>{const rows:TrailmarkSession[]=[];const store={async listActiveSessions(g?:string){return rows.filter(r=>r.active&&(!g||r.guildId===g))},async saveSession(s:TrailmarkSession){rows.push(s)},async deactivateSession(id:string){const row=rows.find(r=>r.id===id);if(row)row.active=false}};let now=new Date("2026-01-01T00:00:00Z");const service=new TrailmarkService(store,{now:()=>now});await service.grant("a","one","member",1000);await service.grant("a","two","member",1000);await service.grant("b","three","member",1000);assert.equal(rows.filter(r=>r.active&&r.guildId==="a").length,1);now=new Date("2026-01-01T00:00:02Z");assert.equal((await service.expire("a")).length,1);assert.equal(rows.find(r=>r.guildId==="b")?.active,true);});
test("Intel remains local when confidential and contacts wait for HQ without duplicates",async()=>{const reports=new Map<string,StoredReport>(),forwards=new Set<string>();const store={async saveReport(r:StoredReport){reports.set(r.id,r)},async getReport(id:string){return reports.get(id)},async hasContactForward(r:string,c:string){return forwards.has(`${r}:${c}`)},async recordContactForward(r:string,c:string){forwards.add(`${r}:${c}`)}};const intel=new IntelService(store);const report=await intel.capture({id:"r",originGuildId:"g",body:"[CONFIDENTIAL] dragon",createdAt:"now",source:"codex",linkedContactIds:["c"],sourceChannelId:"channel",sourceMessageId:"message"},[{id:"t",guildId:"g",name:"Threat",keywords:["dragon"]}]);assert.equal(report.topic,"Threat");const contacts=new ContactForwardingService(store,{async publish(){return"posted"}});assert.deepEqual(await contacts.forward("r"),[]);await intel.markAtHeadquarters("r");assert.deepEqual(await contacts.forward("r"),["c"]);assert.deepEqual(await contacts.forward("r"),[]);let sent=false;assert.equal(await new BridgeService().transfer(report,"[CONFIDENTIAL]",{async send(){sent=true}},"codex-v1"),false);assert.equal(sent,false);});
test("normal reports cross native and legacy bridges",async()=>{const payloads:string[]=[];const report={id:"r",originGuildId:"g",body:"safe",createdAt:"now",source:"codex" as const};const service=new BridgeService();assert.equal(await service.transfer(report,"[SECRET]",{async send(p){payloads.push(p)}},"codex-v1"),true);assert.equal(JSON.parse(payloads[0]!).type,"codex.report");await service.transfer(report,"[SECRET]",{async send(p){payloads.push(p)}},"legacy-wayfinder");assert.equal(JSON.parse(payloads[1]!).content,"safe");});
test("fund ledger balances and undo are persistent operations",async()=>{const rows:LedgerEntry[]=[];const store={async history(){return rows},async append(row:LedgerEntry){rows.push(row)}};const funds=new FundsService(store,{now:()=>new Date("2026-01-01")});await funds.record("g",100,"u","deposit","DEPOSIT");await funds.record("g",30,"u","expense","SPEND");assert.equal(await funds.balance("g"),70);await funds.undoLast("g","u");assert.equal(await funds.balance("g"),100);});
test("fund balance adjustments and monthly summaries preserve ledger auditability",async()=>{const rows:LedgerEntry[]=[];const store={async history(){return rows},async append(row:LedgerEntry){rows.push(row)}};const funds=new FundsService(store,{now:()=>new Date("2026-02-15T00:00:00Z")});await funds.record("g",100,"u","deposit","DEPOSIT");await funds.record("g",25,"u","supplies","SPEND");const adjustment=await funds.setBalance("g",90,"admin","reconciliation");assert.equal(adjustment?.amount,15);assert.equal(await funds.setBalance("g",90,"admin","no change"),undefined);assert.deepEqual(await funds.monthly("g",2026,2),{deposits:100,spending:25,adjustments:15,net:90,count:3});});
test("rank synchronization is not cumulative",()=>{const member={guildId:"g",memberId:"m",displayName:"M",rankId:"r2",status:"ACTIVE" as const,notes:[]};assert.deepEqual(new MemberService().desiredRankRoles(member,[{id:"r1",guildId:"g",name:"First",roleId:"one",tier:"BASELINE"},{id:"r2",guildId:"g",name:"Second",roleId:"two",tier:"LEVEL_1"}]),["two"]);});
test("Atlas link codes expire in ten minutes and disabled modules claim no work",async()=>{let expiry="",claims=0;const gateway={async createLinkCode(_g:string,_m:string,e:string){expiry=e;return"CODE"},async claimAccess(){claims++;return[]as AtlasRequest[]},async completeAccess(){},async claimDrops(){claims++;return[]as AtlasDrop[]},async completeDrop(){}};const atlas=new AtlasService(gateway,{now:()=>new Date("2026-01-01T00:00:00Z")});assert.equal(await atlas.link("g","m",true),"CODE");assert.equal(expiry,"2026-01-01T00:10:00.000Z");assert.deepEqual(await atlas.poll("g",false,async()=>{},async()=>{}),{access:0,drops:0});assert.equal(claims,0);});
