import test from 'node:test';
import assert from 'node:assert/strict';
import { ApplicationFlagsBitField, ChannelType } from 'discord.js';
import { MessageSetupWizard } from '../src/runtime/messageSetup.js';
import type { StoredSetupDraft } from '../src/setup.js';
import { emptyOrganization } from '../src/administration.js';
import { beginConversation } from '../src/runtime/setupConversation.js';
import { SupabaseRepositories } from '../src/persistence/supabase.js';
import { testDatabase } from './database.js';

function fixture(privateThread = false) {
    let draft: StoredSetupDraft | undefined, seq = 1000n, admin = true, intent = true, applied = 0, provisioned = 0, threads = 0, failSend = false;
    const sent: any[] = [], channels = new Map<string, any>();
    function channel(id: string, type: number): any {
        const c: any = { id, type, archived: false, members: { async add() {} }, async setArchived(v: boolean) { c.archived = v; }, permissionsFor: () => ({ has: () => privateThread }),
            threads: { async create(options: any) { assert.equal(options.type, ChannelType.PrivateThread); assert.equal(options.invitable, false); threads++; return channel('thread', ChannelType.PrivateThread); } },
            async send(p: any) { if (failSend) throw new Error('Discord send unavailable'); assert.ok((p.content?.length ?? 0) <= 2000); assert.ok((p.components?.length ?? 0) <= 5); const m = { id: String(++seq), channelId: id, ...p }; sent.push(m); return m; } };
        channels.set(id, c); return c;
    }
    const parent = channel('channel', ChannelType.GuildText);
    const guild: any = { id: 'g', channels: { async fetch(id: string) { return channels.get(id); } }, members: { async fetch() { return { permissions: { has: () => admin } }; }, async fetchMe() { return {}; } }, roles: { async fetch(id?: string) { const role = { id: 'role', name: 'Role', editable: true }; return id ? role : new Map([['role', role]]); } } };
    const store: any = { async load() { return undefined; }, async organization() { return emptyOrganization(); }, async loadSetupDraft() { return draft ? structuredClone(draft) : undefined; }, async saveSetupDraft(d: StoredSetupDraft) { if (draft) assert.equal(d.revision, draft.revision + 1); draft = structuredClone(d); }, async deleteSetupDraft() { draft = undefined; }, async saveOrganization() { applied++; } };
    const provision = async () => { provisioned++; return 'Ready'; };
    let wizard = new MessageSetupWizard(store, provision);
    const client = { options: { intents: { has: () => intent } }, application: { async fetch() { return { flags: new ApplicationFlagsBitField(ApplicationFlagsBitField.Flags.GatewayMessageContentLimited) }; } } };
    const interaction = (action: string, values: string[] = []): any => ({ guildId: 'g', guild, client, channelId: draft?.messageConversation?.channelId ?? 'channel', channel: channels.get(draft?.messageConversation?.channelId ?? 'channel'), user: { id: 'owner', username: 'Owner' }, memberPermissions: { has: () => admin }, customId: `setup:${draft?.revision}:${action}`, message: { id: draft?.messageConversation?.promptId }, values, isModalSubmit: () => false, async deferUpdate() {}, async deferReply() {}, async editReply() {} });
    const message = (content: string, changes: any = {}): any => ({ id: String(++seq), guildId: 'g', guild, channelId: draft?.messageConversation?.channelId ?? 'channel', channel: channels.get(draft?.messageConversation?.channelId ?? 'channel'), author: { id: 'owner', bot: false }, reference: { messageId: draft?.messageConversation?.promptId }, content, ...changes });
    return { store, guild, parent, channels, sent, interaction, message, get draft() { return draft!; }, get wizard() { return wizard; }, get last() { return sent.at(-1); }, get applied() { return applied; }, get provisioned() { return provisioned; }, get threads() { return threads; },
        set admin(v: boolean) { admin = v; }, set intent(v: boolean) { intent = v; }, set failSend(v: boolean) { failSend = v; },
        async start() { await wizard.startInteraction(interaction('')); }, async answer(value: string, changes: any = {}) { await wizard.handleMessage(message(value, changes)); }, async act(action: string, values: string[] = []) { await wizard.handle(interaction(action, values)); },
        restart() { wizard = new MessageSetupWizard(store, provision); },
        async at(step: string, prepare?: (d: StoredSetupDraft) => void) { beginConversation(draft!, step); prepare?.(draft!); await wizard.handle(interaction('resume')); },
    };
}

test('message setup accepts organization and namespace, confirms, persists, then displays role selectors', async () => {
    const f = fixture(); await f.start(); assert.match(f.last.content, /Organization Name/); assert.ok(!JSON.stringify(f.last).includes('guide-text'));
    await f.answer('Order of the Living Story'); assert.equal(f.draft.config.organizationName, 'Order of the Living Story'); assert.match(f.last.content, /Organization Name set to/);
    await f.answer('order'); assert.equal(f.draft.config.commandNamespace, 'order'); assert.match(f.last.content, /Command namespace set to/); assert.equal(f.draft.editor!.conversation!.step, 'permissions');
    assert.equal(f.last.components[0].components[0].type, 6); assert.equal(f.applied, 0); assert.equal(f.provisioned, 0);
});
test('invalid namespace retries without advancing or applying', async () => {
    const f = fixture(); await f.start(); await f.answer('Order'); await f.answer('Invalid Name'); assert.equal(f.draft.config.commandNamespace, undefined); assert.equal(f.draft.editor!.conversation!.step, 'namespace'); assert.match(f.last.content, /Choose 1–32/); await f.answer('order'); assert.equal(f.draft.config.commandNamespace, 'order');
});
for (const [step, value, check] of [
    ['integration', '[LOCAL]', (d: StoredSetupDraft) => d.config.confidentialityMarker],
    ['rank-name', 'Acolyte', (d: StoredSetupDraft) => d.organization!.ranks[0]?.name],
    ['branch-name', 'Progression', (d: StoredSetupDraft) => d.organization!.branches[0]?.name],
    ['group-name', 'Temples', (d: StoredSetupDraft) => d.organization!.groups[0]?.name],
    ['entry-name', 'Green', (d: StoredSetupDraft) => d.organization!.entries[0]?.name],
    ['duty-name', 'Steward', (d: StoredSetupDraft) => d.organization!.duties[0]?.displayName],
    ['resource-name', 'operations', (d: StoredSetupDraft) => d.organization!.additionalResources[0]?.name],
] as const) test(`${step} accepts literal owner message`, async () => {
    const f = fixture(); await f.start(); await f.at(step, d => {
        if (step === 'entry-name') { d.editor!.conversation!.group = 'group'; d.organization!.groups.push({ id: 'group', guildId: 'g', name: 'Group', multiple: false, required: false }); }
        if (step === 'duty-name') { d.editor!.selected = 'role'; d.organization!.duties.push({ guildId: 'g', roleId: 'role', displayName: 'Old' }); }
    }); await f.answer(value); assert.equal(check(f.draft), value); assert.match(f.last.content, /saved|set to/); assert.equal(f.applied, 0);
});
for (const [name, changes] of [
    ['other user', { author: { id: 'other', bot: false } }], ['bot', { author: { id: 'owner', bot: true } }], ['webhook', { webhookId: 'hook' }],
    ['wrong guild', { guildId: 'other' }], ['DM', { guildId: null }], ['wrong channel', { channelId: 'other' }], ['unrelated chat', { reference: undefined }],
    ['reply to old question', { reference: { messageId: '1' } }], ['old message', { id: '1' }],
] as const) test(`setup ignores ${name}`, async () => { const f = fixture(); await f.start(); const before = structuredClone(f.draft); await f.answer('Ignored', changes); assert.deepEqual(f.draft, before); });
test('setup ignores messages without an active session and when a selector is expected', async () => { const f = fixture(); await f.answer('Ignored'); assert.equal(f.draft, undefined); await f.start(); await f.at('permissions'); const before = structuredClone(f.draft); await f.answer('Ignored'); assert.deepEqual(f.draft, before); });
test('message replies check current Administrator permission', async () => { const f = fixture(); await f.start(); f.admin = false; await assert.rejects(f.answer('Denied'), /Administrator/); assert.equal(f.draft.config.organizationName, undefined); });
test('draft expiry blocks messages and components', async () => { const f = fixture(); await f.start(); f.draft.expiresAt = '2000-01-01'; await f.answer('Ignored'); await assert.rejects(f.act('resume'), /expired/); assert.equal(f.draft.config.organizationName, undefined); });
test('burst replies captured at the old revision cannot answer the next question', async () => { const f = fixture(true); await f.start(); const first = f.message('Order', { reference: undefined }), second = f.message('wrong', { reference: undefined }); const revision = f.wizard.messageRevision(second); await f.wizard.handleMessage(first); await f.wizard.handleMessage(second, revision); assert.equal(f.draft.config.organizationName, 'Order'); assert.equal(f.draft.config.commandNamespace, undefined); });
test('private thread is reused and allows unquoted owner replies; cancel archives', async () => { const f = fixture(true); await f.start(); assert.equal(f.threads, 1); await f.answer('Order', { reference: undefined }); await f.start(); assert.equal(f.threads, 1); await f.act('resume'); assert.match(f.last.content, /namespace/); await f.act('cancel'); assert.equal(f.draft, undefined); assert.equal(f.channels.get('thread').archived, true); });
test('restart/resume reconstructs next question and retains accepted answers', async () => { const f = fixture(true); await f.start(); await f.answer('Order'); f.restart(); await f.answer('Ignored'); assert.equal(f.draft.config.commandNamespace, undefined); await f.start(); assert.match(f.last.content, /unfinished/); await f.act('resume'); assert.match(f.last.content, /namespace/); assert.equal(f.draft.config.organizationName, 'Order'); assert.equal(f.threads, 1); await f.answer('order'); assert.equal(f.draft.config.commandNamespace, 'order'); });
test('Back displays saved value and Keep Current advances without erasing it', async () => { const f = fixture(); await f.start(); await f.answer('Order'); await f.act('guide-back'); assert.match(f.last.content, /Current value: \*\*Order/); assert.match(JSON.stringify(f.last.components), /Keep Current/); await f.act('keep'); assert.equal(f.draft.config.organizationName, 'Order'); assert.equal(f.draft.editor!.conversation!.step, 'namespace'); });
test('Skip only advances optional sections, Cancel changes no production configuration', async () => { const f = fixture(); await f.start(); await f.act('guide-skip'); assert.equal(f.draft.editor!.conversation!.step, 'identity'); await f.at('ranks'); await f.act('guide-skip'); assert.equal(f.draft.editor!.conversation!.step, 'branches'); await f.act('cancel'); assert.equal(f.draft, undefined); assert.equal(f.applied, 0); });
test('stale components, copied components and nonowners cannot change setup', async () => { const f = fixture(); await f.start(); const old = f.interaction('cancel'); await f.answer('Order'); await assert.rejects(f.wizard.handle(old), /stale/); const copied = f.interaction('cancel'); copied.channelId = 'elsewhere'; await assert.rejects(f.wizard.handle(copied), /stale/); const other = f.interaction('cancel'); other.user.id = 'other'; await assert.rejects(f.wizard.handle(other), /owner/); });
test('durable revision and expected-question mismatch reject messages', async () => { const f = fixture(); await f.start(); f.draft.revision++; await f.answer('Ignored'); assert.equal(f.draft.config.organizationName, undefined); await f.start(); await f.act('resume'); f.draft.editor!.conversation!.step = 'namespace'; await f.answer('ignored'); assert.equal(f.draft.config.commandNamespace, undefined); });
test('missing Message Content intent gives actionable error without creating a draft', async () => { const f = fixture(); f.intent = false; await assert.rejects(f.start(), /Developer Portal/); assert.equal(f.draft, undefined); });
test('empty and oversized replies do not advance', async () => { const f = fixture(); await f.start(); const rev = f.draft.revision; await f.answer(''); await f.answer('a'.repeat(101)); assert.ok(f.draft.revision > rev); assert.equal(f.draft.config.organizationName, undefined); assert.match(f.last.content, /1–100/); });
test('role and channel selectors retain their draft behavior', async () => { const f = fixture(); await f.start(); await f.at('permissions'); await f.act('guide-answer', ['role']); assert.equal(f.draft.organization!.permissions[0]?.roleId, 'role'); await f.at('resources'); assert.equal(f.last.components[0].components[0].type, 8); await f.act('guide-answer', ['channel']); assert.equal(f.draft.organization!.resources[0]?.discordId, 'channel'); assert.equal(f.applied, 0); });
test('final review and explicit confirmation are still required', async () => { const f = fixture(); await f.start(); await f.answer('Order'); await f.answer('order'); await f.act('confirm'); assert.equal(f.applied, 0); await f.act('guide-review'); assert.match(f.last.content, /Confirm Setup/); assert.equal(f.applied, 0); await f.act('confirm'); assert.equal(f.applied, 1); assert.equal(f.provisioned, 1); assert.equal(f.draft, undefined); });
test('detailed editor text forms use messages and Keep Current', async () => { const f = fixture(); await f.start(); await f.answer('Order'); await f.act('advanced'); await f.act('text'); assert.match(f.last.content, /Configure identity/); await f.answer('New Order'); assert.equal(f.draft.config.organizationName, 'New Order'); await f.act('text'); await f.act('keep'); assert.equal(f.draft.config.organizationName, 'New Order'); assert.equal(f.applied, 0); });
test('failed question send leaves accepted answer durable and old prompt inert', async () => { const f = fixture(); await f.start(); f.failSend = true; await assert.rejects(f.answer('Order'), /send unavailable/); assert.equal(f.draft.config.organizationName, 'Order'); assert.equal(f.draft.messageConversation!.promptId, undefined); f.failSend = false; await f.start(); await f.act('resume'); assert.match(f.last.content, /namespace/); });
test('Start Over reuses the bound conversation and resets only the draft', async () => { const f = fixture(true); await f.start(); await f.answer('Order'); await f.act('restart'); await f.answer('Ignored'); assert.equal(f.draft.config.organizationName, 'Order'); await f.act('restart-confirm'); assert.equal(f.draft.config.organizationName, undefined); assert.equal(f.threads, 1); await f.answer('New'); assert.equal(f.draft.config.organizationName, 'New'); });
test('existing SQL draft RPC persists message binding with strict revisions', async () => { const f = fixture(); await f.start(); await f.answer('Order'); const { db, client } = await testDatabase(); try { const repo = new SupabaseRepositories(client); const d = structuredClone(f.draft); d.revision = 0; await repo.saveSetupDraft(d); const rows = await db.query<{ payload: StoredSetupDraft }>('select payload from setup_drafts where guild_id = $1', ['g']); assert.deepEqual(rows.rows[0]!.payload.messageConversation, d.messageConversation); assert.equal(rows.rows[0]!.payload.config.organizationName, 'Order'); await assert.rejects(repo.saveSetupDraft(d)); } finally { await db.close(); } });

test('pending detailed text question survives restart and resumes without a modal', async () => {
    const f = fixture(); await f.start(); await f.act('advanced'); await f.act('section', ['resources']); await f.act('new'); f.restart(); await f.start(); await f.act('resume'); assert.match(f.last.content, /Configure resources/); await f.answer('new-channel'); assert.equal(f.draft.organization!.additionalResources[0]?.name, 'new-channel'); assert.match(f.last.content, /Value set to/);
});
test('Back from detailed text leaves text capture and retains selected entity', async () => { const f = fixture(); await f.start(); await f.act('advanced'); await f.act('section', ['ranks']); await f.act('new'); await assert.rejects(f.act('keep'), /no current value/); await f.act('text-back'); const before = structuredClone(f.draft); await f.answer('Ignored'); assert.deepEqual(f.draft, before); assert.equal(f.draft.messageConversation!.textPrompt, undefined); });
test('Back can replace branch name without creating a second branch', async () => { const f = fixture(); await f.start(); await f.at('branch-name'); await f.answer('Old'); await f.act('guide-back'); assert.match(f.last.content, /Current value: \*\*Old/); await f.answer('New'); assert.equal(f.draft.organization!.branches.length, 1); assert.equal(f.draft.organization!.branches[0]!.name, 'New'); });
test('private thread completion archives the conversation after explicit confirmation', async () => { const f = fixture(true); await f.start(); await f.answer('Order'); await f.answer('order'); await f.act('guide-review'); await f.act('confirm'); assert.equal(f.channels.get('thread').archived, true); assert.equal(f.applied, 1); });
test('fake modal and text select cannot bypass the bound message route', async () => { const f = fixture(); await f.start(); const modal = f.interaction('guide-answer'); modal.isModalSubmit = () => true; await assert.rejects(f.wizard.handle(modal), /Reply/); await assert.rejects(f.act('guide-answer', ['bad']), /Reply/); assert.equal(f.draft.config.organizationName, undefined); });
test('failed thread creation falls back without retrying duplicate creation', async () => { const f = fixture(true); let attempts = 0; f.parent.threads.create = async () => { attempts++; throw new Error('Unknown network outcome'); }; await f.start(); assert.equal(f.draft.messageConversation!.privateThread, false); assert.match(f.last.content, /Discord Reply/); await f.start(); assert.equal(attempts, 1); await f.act('resume'); await f.answer('Order'); assert.equal(f.draft.config.organizationName, 'Order'); });
test('a lost thread rebinds the saved draft to the invocation channel', async () => { const f = fixture(true); await f.start(); await f.answer('Order'); f.channels.delete('thread'); const i = f.interaction(''); i.channelId = 'channel'; i.channel = f.parent; await f.wizard.startInteraction(i); assert.equal(f.threads, 1); assert.equal(f.draft.messageConversation!.channelId, 'channel'); await f.act('resume'); assert.match(f.last.content, /namespace/); assert.equal(f.draft.config.organizationName, 'Order'); });
test('SQL-style errors stay out of setup replies', async () => { const f = fixture(); await f.start(); const original = f.store.saveSetupDraft; let fail = true; f.store.saveSetupDraft = async (d: StoredSetupDraft) => { if (fail) { fail = false; throw new Error('postgres column secret_token in setup_drafts failed'); } await original(d); }; await f.answer('Order'); assert.doesNotMatch(f.last.content, /secret_token|postgres|column/); assert.equal(f.draft.config.organizationName, undefined); await f.answer('Order'); assert.equal(f.draft.config.organizationName, 'Order'); });
test('prompt-binding save failure leaves an orphan prompt inert until Resume', async () => { const f = fixture(); await f.start(); const original = f.store.saveSetupDraft; let fail = true; f.store.saveSetupDraft = async (d: StoredSetupDraft) => { if (fail && d.messageConversation?.promptId && d.config.organizationName === 'Order' && d.messageConversation.revision === d.revision) { fail = false; throw new Error('Storage unavailable'); } await original(d); }; await assert.rejects(f.answer('Order'), /Storage unavailable/); assert.equal(f.draft.config.organizationName, 'Order'); await f.answer('Ignored'); assert.equal(f.draft.config.commandNamespace, undefined); await f.start(); await f.act('resume'); await f.answer('order'); assert.equal(f.draft.config.commandNamespace, 'order'); });

test('detailed text expectation remains durable across repeated resume and invalid answers', async () => {
    const f = fixture(); await f.start(); await f.act('advanced'); await f.act('section', ['namespace']); await f.act('text');
    for (let n = 0; n < 2; n++) { f.restart(); await f.start(); await f.act('resume'); assert.equal(f.draft.messageConversation!.textPrompt?.action, 'save-text'); }
    await f.answer('Invalid Namespace'); assert.equal(f.draft.config.commandNamespace, undefined); assert.equal(f.draft.messageConversation!.textPrompt?.action, 'save-text');
    f.restart(); await f.start(); await f.act('resume'); await f.answer('order'); assert.equal(f.draft.config.commandNamespace, 'order'); assert.equal(f.draft.messageConversation!.textPrompt, undefined);
});
test('private thread creation requires both thread permissions', async () => { const f = fixture(true); f.parent.permissionsFor = () => ({ has: () => false }); await f.start(); assert.equal(f.threads, 0); assert.equal(f.draft.messageConversation!.privateThread, false); await f.answer('Ignored', { reference: undefined }); assert.equal(f.draft.config.organizationName, undefined); await f.answer('Order'); assert.equal(f.draft.config.organizationName, 'Order'); });
