import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ModalBuilder, TextInputBuilder, TextInputStyle } from "discord.js";
import { beginSetup, preview, updateDraft, validateForConfirmation, type SetupDraft, type SetupStage, type StoredSetupDraft } from "../setup.js";
import type { ServerConfig } from "../domain.js";

export interface SetupStore {
  load(guildId:string):Promise<ServerConfig|undefined>; save(config:ServerConfig):Promise<void>;
  loadSetupDraft?(guildId:string):Promise<StoredSetupDraft|undefined>;
  saveSetupDraft?(draft:StoredSetupDraft):Promise<void>;
  deleteSetupDraft?(guildId:string,ownerId?:string):Promise<void>;
}
const stages: SetupStage[]=["identity","namespace","permissions","ranks","duties","assignments","modules","resources","destinations","integration","preview","confirmation","provisioning"];
export class SetupWizard {
  private readonly drafts=new Map<string,StoredSetupDraft>();
  constructor(private readonly store:SetupStore,private readonly provision:(config:ServerConfig)=>Promise<string>){}
  async start(guildId:string,ownerId="unknown"){const existing=await this.store.load(guildId);let draft=await this.store.loadSetupDraft?.(guildId);if(draft&&Date.parse(draft.expiresAt)<=Date.now()){await this.store.deleteSetupDraft?.(guildId);draft=undefined;}if(draft&&draft.ownerId!==ownerId)throw new Error("Another administrator owns the active setup draft");if(!draft){const initial=beginSetup(existing);draft={...initial,guildId,ownerId,updatedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+7*86400000).toISOString()};await this.persist(draft);}this.drafts.set(guildId,draft);return{content:existing?"Configuration exists. View, edit, repair, or cancel.":`Codex setup: ${draft.stage}${draft.revision?" (resumed)":""}`,ephemeral:true,components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("setup:edit").setLabel(existing?"Edit":"Continue").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("setup:view").setLabel("View").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("setup:repair").setLabel("Repair").setStyle(ButtonStyle.Secondary).setDisabled(!existing),new ButtonBuilder().setCustomId("setup:cancel").setLabel("Cancel").setStyle(ButtonStyle.Danger))]};}
  async modal(guildId:string):Promise<any>{const draft=await this.required(guildId);const modal=new ModalBuilder().setCustomId(`setup:stage:${draft.stage}`).setTitle(`Setup: ${draft.stage}`);const fields=this.fields(draft);for(const [id,label,value] of fields)modal.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(id).setLabel(label).setStyle(TextInputStyle.Short).setRequired(true).setValue(value)));return modal;}
  async submit(guildId:string,values:Record<string,string>):Promise<{content:string;done?:boolean;components?:any[]}>{let draft=await this.required(guildId);const index=stages.indexOf(draft.stage);let next:SetupDraft;if(draft.stage==="identity")next=updateDraft(draft,{guildId,organizationName:required(values,"organizationName")},"namespace");else if(draft.stage==="namespace")next=updateDraft(draft,{commandNamespace:required(values,"commandNamespace")},"permissions");else if(draft.stage==="integration")next=updateDraft(draft,{confidentialityMarker:required(values,"confidentialityMarker"),modules:draft.config.modules??{briefings:false,patrols:false,supply:false,atlas:false}},"preview");else next={...draft,stage:stages[index+1]??"preview",revision:draft.revision+1};draft={...draft,...next,updatedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+7*86400000).toISOString()};await this.persist(draft);if(draft.stage==="preview")return{content:`${preview(draft)}\nNo Discord resources have been changed. Confirm to provision.`,components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("setup:confirm").setLabel("Confirm and provision").setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId("setup:cancel").setLabel("Cancel").setStyle(ButtonStyle.Danger))]};return{content:`Saved durably. Next stage: ${draft.stage}`};}
  async confirm(guildId:string,ownerId?:string):Promise<string>{const draft=await this.required(guildId);if(ownerId&&draft.ownerId!==ownerId)throw new Error("Only the draft owner may confirm setup");validateForConfirmation(draft);await this.store.save(draft.config);const result=await this.provision(draft.config);await this.store.deleteSetupDraft?.(guildId);this.drafts.delete(guildId);return result;}
  async cancel(guildId:string,ownerId?:string):Promise<void>{const draft=await this.required(guildId);if(ownerId&&draft.ownerId!==ownerId)throw new Error("Only the draft owner may cancel setup");await this.store.deleteSetupDraft?.(guildId,ownerId);this.drafts.delete(guildId);}
  async view(guildId:string):Promise<string>{return preview(await this.required(guildId));}
  private async persist(draft:StoredSetupDraft){this.drafts.set(draft.guildId,draft);await this.store.saveSetupDraft?.(draft);}
  private async required(guildId:string){let draft=this.drafts.get(guildId);draft??=await this.store.loadSetupDraft?.(guildId);if(!draft)throw new Error("Start /server setup first");this.drafts.set(guildId,draft);return draft;}
  private fields(draft:SetupDraft):Array<[string,string,string]>{if(draft.stage==="identity")return[["organizationName","Organization name",draft.config.organizationName??""]];if(draft.stage==="namespace")return[["commandNamespace","Command namespace",draft.config.commandNamespace??""]];if(draft.stage==="integration")return[["confidentialityMarker","Confidentiality marker",draft.config.confidentialityMarker??"[CONFIDENTIAL]"]];return[["configuration","Configuration JSON / selected IDs",""]];}
}
function required(values:Record<string,string>,key:string):string{const value=values[key]?.trim();if(!value)throw new Error(`${key} is required`);return value;}
