import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ModalBuilder, TextInputBuilder, TextInputStyle } from "discord.js";
import { beginSetup, preview, updateDraft, validateForConfirmation, type SetupDraft, type SetupStage } from "../setup.js";
import type { ServerConfig } from "../domain.js";

export interface SetupStore { load(guildId:string):Promise<ServerConfig|undefined>; save(config:ServerConfig):Promise<void> }
const stages: SetupStage[]=["identity","namespace","permissions","ranks","duties","assignments","modules","resources","destinations","integration","preview","confirmation","provisioning"];
export class SetupWizard {
  private readonly drafts=new Map<string,SetupDraft>();
  constructor(private readonly store:SetupStore,private readonly provision:(config:ServerConfig)=>Promise<string>){}
  async start(guildId:string){const existing=await this.store.load(guildId);this.drafts.set(guildId,beginSetup(existing));return{content:existing?"Configuration exists. View, edit, repair, or cancel.":"Codex setup: organization identity",ephemeral:true,components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("setup:edit").setLabel(existing?"Edit":"Begin").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("setup:view").setLabel("View").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("setup:repair").setLabel("Repair").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("setup:cancel").setLabel("Cancel").setStyle(ButtonStyle.Danger))]};}
  modal(guildId:string):any{const draft=this.required(guildId);const modal=new ModalBuilder().setCustomId(`setup:stage:${draft.stage}`).setTitle(`Setup: ${draft.stage}`);const fields=this.fields(draft);for(const [id,label,value] of fields)modal.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(id).setLabel(label).setStyle(TextInputStyle.Short).setRequired(true).setValue(value)));return modal;}
  async submit(guildId:string,values:Record<string,string>):Promise<{content:string;done?:boolean}>{let draft=this.required(guildId);const index=stages.indexOf(draft.stage);if(draft.stage==="identity")draft=updateDraft(draft,{guildId,organizationName:required(values,"organizationName")},"namespace");else if(draft.stage==="namespace")draft=updateDraft(draft,{commandNamespace:required(values,"commandNamespace")},"permissions");else if(draft.stage==="integration")draft=updateDraft(draft,{confidentialityMarker:required(values,"confidentialityMarker"),modules:draft.config.modules??{briefings:false,patrols:false,supply:false,atlas:false}},"preview");else draft={...draft,stage:stages[index+1]??"preview",revision:draft.revision+1};this.drafts.set(guildId,draft);if(draft.stage==="preview")return{content:`${preview(draft)}\nConfirm to provision.`};return{content:`Saved. Next stage: ${draft.stage}`};}
  async confirm(guildId:string):Promise<string>{const draft=this.required(guildId);validateForConfirmation(draft);await this.store.save(draft.config);return this.provision(draft.config);}
  view(guildId:string):string{return preview(this.required(guildId));}
  private required(guildId:string){const draft=this.drafts.get(guildId);if(!draft)throw new Error("Start /server setup first");return draft;}
  private fields(draft:SetupDraft):Array<[string,string,string]>{if(draft.stage==="identity")return[["organizationName","Organization name",draft.config.organizationName??""]];if(draft.stage==="namespace")return[["commandNamespace","Command namespace",draft.config.commandNamespace??""]];if(draft.stage==="integration")return[["confidentialityMarker","Confidentiality marker",draft.config.confidentialityMarker??"[CONFIDENTIAL]"]];return[["configuration","Configuration JSON / selected IDs",""]];}
}
function required(values:Record<string,string>,key:string):string{const value=values[key]?.trim();if(!value)throw new Error(`${key} is required`);return value;}
