-- Bot-side contracts. Browser callers require an authenticated service gateway;
-- none of these functions grant arbitrary public access to service-managed state.
create table atlas_identities(guild_id text not null references server_config on delete cascade,atlas_user_id text not null,discord_user_id text not null,linked_at timestamptz not null default now(),primary key(guild_id,atlas_user_id),unique(guild_id,discord_user_id));
create table atlas_profiles(guild_id text not null,discord_user_id text not null,profile jsonb not null,presence text not null default 'unknown',updated_at timestamptz not null default now(),primary key(guild_id,discord_user_id));
create table atlas_visits(id uuid primary key default gen_random_uuid(),guild_id text not null references server_config on delete cascade,discord_user_id text not null,trailmark_id uuid not null references trailmarks on delete cascade,session_id uuid not null references trailmark_sessions on delete cascade,started_at timestamptz not null default now(),last_seen_at timestamptz not null default now(),ended_at timestamptz,unique(session_id));
create table atlas_live_positions(guild_id text not null,atlas_user_id text not null,position jsonb not null,updated_at timestamptz not null default now(),primary key(guild_id,atlas_user_id),foreign key(guild_id,atlas_user_id) references atlas_identities on delete cascade);
alter table atlas_trailmark_access_requests add column lease_until timestamptz,add column attempts integer not null default 0,add column session_id uuid references trailmark_sessions;
alter table atlas_trailmark_drops add column lease_until timestamptz,add column attempts integer not null default 0;
create or replace function codex_atlas_enabled(p_guild text) returns void language plpgsql set search_path=public as $$begin if not exists(select 1 from server_modules where guild_id=p_guild and module_key='atlas' and enabled) then raise exception 'Atlas module is disabled';end if;end $$;
create or replace function create_atlas_discord_link_code(p_guild_id text,p_discord_user_id text,p_expires_at timestamptz) returns text language plpgsql set search_path=public as $$declare code text:=replace(gen_random_uuid()::text,'-','');begin
 perform codex_atlas_enabled(p_guild_id);if p_expires_at<=now() or p_expires_at>now()+interval '10 minutes 5 seconds' then raise exception 'Link codes expire within ten minutes';end if;
 delete from atlas_discord_links where guild_id=p_guild_id and discord_user_id=p_discord_user_id and claimed_at is null;
 insert into atlas_discord_links(guild_id,discord_user_id,code_hash,expires_at) values(p_guild_id,p_discord_user_id,encode(sha256(convert_to(code,'UTF8')),'hex'),p_expires_at);return code;end $$;
create or replace function claim_atlas_discord_link(p_guild_id text,p_atlas_user_id text,p_code text) returns jsonb language plpgsql set search_path=public as $$declare link atlas_discord_links;begin
 perform codex_atlas_enabled(p_guild_id);select * into link from atlas_discord_links where guild_id=p_guild_id and code_hash=encode(sha256(convert_to(p_code,'UTF8')),'hex') and expires_at>now() and claimed_at is null for update;
 if not found then raise exception 'Link code is invalid, expired, or consumed';end if;
 insert into atlas_identities values(p_guild_id,p_atlas_user_id,link.discord_user_id,now());update atlas_discord_links set claimed_at=now() where id=link.id;return jsonb_build_object('guildId',p_guild_id,'memberId',link.discord_user_id);end $$;
create or replace function get_atlas_discord_link(p_guild_id text,p_discord_user_id text) returns jsonb language sql set search_path=public as $$select to_jsonb(x) from atlas_identities x where guild_id=p_guild_id and discord_user_id=p_discord_user_id$$;
create or replace function unlink_atlas_discord(p_guild_id text,p_discord_user_id text) returns void language plpgsql set search_path=public as $$begin
 delete from atlas_identities where guild_id=p_guild_id and discord_user_id=p_discord_user_id;delete from atlas_discord_links where guild_id=p_guild_id and discord_user_id=p_discord_user_id;
 update atlas_trailmark_access_requests set status='REJECTED',detail='Discord link removed' where guild_id=p_guild_id and discord_user_id=p_discord_user_id and status in('PENDING','PROCESSING');update atlas_trailmark_drops set status='REJECTED',detail='Discord link removed' where guild_id=p_guild_id and discord_user_id=p_discord_user_id and status in('PENDING','PROCESSING');end $$;
create or replace function request_atlas_trailmark_access(p_guild_id text,p_atlas_user_id text,p_trailmark_id uuid,p_request_id uuid) returns uuid language plpgsql set search_path=public as $$declare member text;begin
 perform codex_atlas_enabled(p_guild_id);select discord_user_id into member from atlas_identities where guild_id=p_guild_id and atlas_user_id=p_atlas_user_id;if member is null or not exists(select 1 from trailmarks where guild_id=p_guild_id and id=p_trailmark_id and active) then raise exception 'Linked member and active local Trailmark required';end if;
 insert into atlas_trailmark_access_requests(id,guild_id,discord_user_id,trailmark_id) values(p_request_id,p_guild_id,member,p_trailmark_id) on conflict(id) do nothing;if not exists(select 1 from atlas_trailmark_access_requests where id=p_request_id and guild_id=p_guild_id and discord_user_id=member and trailmark_id=p_trailmark_id) then raise exception 'Request identity conflict';end if;return p_request_id;end $$;
create or replace function submit_atlas_trailmark_drop(p_guild_id text,p_atlas_user_id text,p_trailmark_id uuid,p_drop_id uuid,p_payload jsonb) returns uuid language plpgsql set search_path=public as $$declare member text;begin
 perform codex_atlas_enabled(p_guild_id);select discord_user_id into member from atlas_identities where guild_id=p_guild_id and atlas_user_id=p_atlas_user_id;
 if member is null or not exists(select 1 from trailmarks where guild_id=p_guild_id and id=p_trailmark_id and active) or jsonb_typeof(p_payload->'body') is distinct from 'string' or length(trim(p_payload->>'body')) not between 1 and 4000 then raise exception 'Linked member, active Trailmark and bounded report body required';end if;
 insert into atlas_trailmark_drops(id,guild_id,discord_user_id,trailmark_id,payload) values(p_drop_id,p_guild_id,member,p_trailmark_id,p_payload) on conflict(id) do nothing;if not exists(select 1 from atlas_trailmark_drops where id=p_drop_id and guild_id=p_guild_id and discord_user_id=member and trailmark_id=p_trailmark_id) then raise exception 'Drop identity conflict';end if;return p_drop_id;end $$;
create or replace function claim_pending_atlas_trailmark_access_requests(p_guild_id text) returns jsonb language plpgsql set search_path=public as $$declare result jsonb;begin perform codex_atlas_enabled(p_guild_id);
 update atlas_trailmark_access_requests set status='REJECTED',detail='Lease recovery exhausted' where guild_id=p_guild_id and status='PROCESSING' and lease_until<now() and attempts>=5;
 with picked as(select id from atlas_trailmark_access_requests where guild_id=p_guild_id and (status='PENDING' or status='PROCESSING' and lease_until<now()) and attempts<5 order by created_at,id limit 25 for update skip locked),claimed as(update atlas_trailmark_access_requests set status='PROCESSING',lease_until=now()+interval '30 seconds',attempts=attempts+1 where id in(select id from picked) returning *) select coalesce(jsonb_agg(jsonb_build_object('id',id,'guildId',guild_id,'memberId',discord_user_id,'trailmarkId',trailmark_id)),'[]') into result from claimed;return result;end $$;
create or replace function claim_pending_atlas_trailmark_drops(p_guild_id text) returns jsonb language plpgsql set search_path=public as $$declare result jsonb;begin perform codex_atlas_enabled(p_guild_id);
 update atlas_trailmark_drops set status='REJECTED',detail='Lease recovery exhausted' where guild_id=p_guild_id and status='PROCESSING' and lease_until<now() and attempts>=5;
 with picked as(select id from atlas_trailmark_drops where guild_id=p_guild_id and (status='PENDING' or status='PROCESSING' and lease_until<now()) and attempts<5 order by created_at,id limit 25 for update skip locked),claimed as(update atlas_trailmark_drops set status='PROCESSING',lease_until=now()+interval '30 seconds',attempts=attempts+1 where id in(select id from picked) returning *) select coalesce(jsonb_agg(jsonb_build_object('id',id,'guildId',guild_id,'memberId',discord_user_id,'trailmarkId',trailmark_id,'payload',payload)),'[]') into result from claimed;return result;end $$;
create or replace function complete_atlas_trailmark_access_request(p_request_id uuid,p_success boolean,p_detail text default null) returns void language sql set search_path=public as $$update atlas_trailmark_access_requests set status=case when p_success then 'COMPLETED' when attempts>=5 then 'REJECTED' else 'PENDING' end,detail=left(p_detail,500),lease_until=null where id=p_request_id and status='PROCESSING'$$;
create or replace function complete_atlas_trailmark_drop(p_drop_id uuid,p_success boolean,p_detail text default null) returns void language sql set search_path=public as $$update atlas_trailmark_drops set status=case when p_success then 'COMPLETED' when attempts>=5 then 'REJECTED' else 'PENDING' end,detail=left(p_detail,500),lease_until=null where id=p_drop_id and status='PROCESSING'$$;
create or replace function get_atlas_trailmark_access_request(p_guild_id text,p_discord_user_id text,p_request_id uuid) returns jsonb language sql set search_path=public as $$select to_jsonb(x) from atlas_trailmark_access_requests x where guild_id=p_guild_id and discord_user_id=p_discord_user_id and id=p_request_id$$;
create or replace function get_atlas_trailmark_drop(p_guild_id text,p_discord_user_id text,p_drop_id uuid) returns jsonb language sql set search_path=public as $$select to_jsonb(x) from atlas_trailmark_drops x where guild_id=p_guild_id and discord_user_id=p_discord_user_id and id=p_drop_id$$;
create or replace function record_atlas_trailmark_visit(p_guild_id text,p_discord_user_id text,p_trailmark_id uuid,p_session_id uuid) returns uuid language plpgsql set search_path=public as $$declare result uuid;begin
 perform codex_atlas_enabled(p_guild_id);if not exists(select 1 from trailmark_sessions where id=p_session_id and guild_id=p_guild_id and discord_member_id=p_discord_user_id and trailmark_id=p_trailmark_id and state='ACTIVE' and expires_at>now()) then raise exception 'An active local session is required';end if;
 insert into atlas_visits(guild_id,discord_user_id,trailmark_id,session_id) values(p_guild_id,p_discord_user_id,p_trailmark_id,p_session_id) on conflict(session_id) do update set last_seen_at=now(),ended_at=null returning id into result;return result;end $$;
create or replace function touch_atlas_trailmark_visit(p_guild_id text,p_discord_user_id text,p_visit_id uuid) returns void language sql set search_path=public as $$update atlas_visits v set last_seen_at=now() where v.id=p_visit_id and v.guild_id=p_guild_id and v.discord_user_id=p_discord_user_id and v.ended_at is null and exists(select 1 from trailmark_sessions s where s.id=v.session_id and s.state='ACTIVE' and s.expires_at>now())$$;
create or replace function upsert_atlas_live_position(p_guild_id text,p_atlas_user_id text,p_position jsonb) returns void language plpgsql set search_path=public as $$begin
 perform codex_atlas_enabled(p_guild_id);if jsonb_typeof(p_position)<>'object' or exists(select 1 from unnest(array['x','y','z']) k where jsonb_typeof(p_position->k) is distinct from 'number' or abs((p_position->>k)::numeric)>1000000000) then raise exception 'Bounded numeric x/y/z required';end if;
 insert into atlas_live_positions values(p_guild_id,p_atlas_user_id,p_position,now()) on conflict(guild_id,atlas_user_id) do update set position=excluded.position,updated_at=now();end $$;
create or replace function remove_atlas_live_position(p_guild_id text,p_atlas_user_id text) returns void language sql set search_path=public as $$delete from atlas_live_positions where guild_id=p_guild_id and atlas_user_id=p_atlas_user_id$$;
create or replace function get_atlas_live_positions(p_guild_id text) returns jsonb language sql set search_path=public as $$select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(select * from atlas_live_positions where guild_id=p_guild_id and updated_at>now()-interval '2 minutes' order by updated_at desc limit 100)x$$;
create or replace function codex_atlas(p_guild text,p_action text,p_member text,p_id uuid default null,p_data jsonb default '{}') returns jsonb language plpgsql set search_path=public as $$declare request atlas_trailmark_access_requests;s jsonb;begin
 perform codex_atlas_enabled(p_guild);
 if p_action='grant' then
  select * into request from atlas_trailmark_access_requests where id=p_id and guild_id=p_guild and discord_user_id=p_member and status='PROCESSING' for update;if not found then raise exception 'Claimed access request not found';end if;
  if not exists(select 1 from atlas_identities where guild_id=p_guild and discord_user_id=p_member) then raise exception 'Discord identity is no longer linked';end if;
  if request.session_id is not null then return (select to_jsonb(x) from trailmark_sessions x where id=request.session_id);end if;
  s:=codex_trailmarks(p_guild,'access',p_member,request.trailmark_id);update atlas_trailmark_access_requests set session_id=(s->>'id')::uuid where id=request.id;return s;
 elsif p_action='profiles' then return coalesce((select jsonb_agg(to_jsonb(x)) from(select * from atlas_identities where guild_id=p_guild order by discord_user_id limit 10 offset greatest(0,coalesce((p_data->>'page')::integer,0))*10)x),'[]');
 elsif p_action='profile' then
  if not exists(select 1 from atlas_identities where guild_id=p_guild and discord_user_id=p_member) then raise exception 'Discord member is not linked';end if;
  insert into atlas_profiles values(p_guild,p_member,p_data->'profile',coalesce(p_data->>'presence','unknown'),now()) on conflict(guild_id,discord_user_id) do update set profile=excluded.profile,presence=excluded.presence,updated_at=now();return '{}';
 elsif p_action='heartbeat' then
  update atlas_visits v set ended_at=now() where guild_id=p_guild and ended_at is null and not exists(select 1 from trailmark_sessions s where s.id=v.session_id and s.state='ACTIVE' and s.expires_at>now());
  return coalesce((select jsonb_agg(to_jsonb(x)) from(select * from trailmark_sessions where guild_id=p_guild and discord_member_id=p_member and state='ACTIVE' and expires_at>now() limit 1)x),'[]');
 elsif p_action='status' then return jsonb_build_object('link',get_atlas_discord_link(p_guild,p_member),'access',coalesce((select jsonb_agg(to_jsonb(x)) from(select id,status,detail,created_at from atlas_trailmark_access_requests where guild_id=p_guild and discord_user_id=p_member order by created_at desc limit 5)x),'[]'),'drops',coalesce((select jsonb_agg(to_jsonb(x)) from(select id,status,detail,created_at from atlas_trailmark_drops where guild_id=p_guild and discord_user_id=p_member order by created_at desc limit 5)x),'[]'));
 else raise exception 'Unknown Atlas action';end if;
end $$;
do $$ declare t text;f record;begin
 foreach t in array array['atlas_identities','atlas_profiles','atlas_visits','atlas_live_positions'] loop execute format('alter table %I enable row level security',t);execute format('grant select,insert,update,delete on %I to service_role',t);end loop;
 for f in select oid::regprocedure signature from pg_proc where pronamespace='public'::regnamespace and (proname like '%atlas%') loop execute format('revoke all on function %s from public,anon,authenticated',f.signature);execute format('grant execute on function %s to service_role',f.signature);end loop;
end $$;
